version: 0.2

phases:
  pre_build:
    commands:
      - cd api
      - npm install

  build:
    commands:
      - npm run build

cache:
  paths:
    - "node_modules/**/*"

artifacts:
  files:
    - "**/*"
base-directory: ./
