version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=ferin
      - RABBITMQ_DEFAULT_PASS=patel
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  web:
    image: fairknock_job:latest
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
